---
name: "🐛 Bug Report"
description: Report a bug
title: "(short issue description)"
labels: [bug]
assignees: []
body:
  - type: textarea
    id: workloadtype
    attributes:
      label: Training or Inference
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: jnstancetype
    attributes:
      label: Instance Type
      description: What instance type are you using? (e.g.Inf2.xlarge/trn1.32xlarge/trn2.48xlarge etc.)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: releaseversion
    attributes:
      label: Release Version
      description: Which release version are you using? (e.g. Release_2.24.0, Release_2.25.0, etc.)    
    validations:
      required: true
  - type: textarea
    id: link
    attributes:
      label: Sample link
      description: Please include a link to the sample code that reproduces the issue.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reproduction Steps
      description: Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
      If applicable, include the command used to run the code and any relevant environment variables or configurations.  
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Attach relevant logs
      description: Please attach relevant logs.
      validations:
       required: true

 
 
  
  
  
      